### ISSUE TITLE
Cannot install nasapower

### ISSUE THREAD

**Issue by 1nd1nd1** [adamhsparks/nasapower#12]
Hi @adamhsparks , when I try to install nasapower, i get the following message and fail to install the package:

---------------------------------------------------------------------------
> library(devtools)
> devtools::install_github("adamhsparks/nasapower", build_vignettes = TRUE)

Downloading GitHub repo adamhsparks/nasapower@master
from URL https://api.github.com/repos/adamhsparks/nasapower/zipball/master
Installing nasapower
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD build  \
  '/private/var/folders/f_/hrv_rbld7w74b42yz8psmmv40000gn/T/RtmpFFlUrZ/devtools808a2043affd/adamhsparks-nasapower-63edbdc'  \
  --no-resave-data --no-manual 

* checking for file ‘/private/var/folders/f_/hrv_rbld7w74b42yz8psmmv40000gn/T/RtmpFFlUrZ/devtools808a2043affd/adamhsparks-nasapower-63edbdc/DESCRIPTION’ ... OK
* preparing ‘nasapower’:
* checking DESCRIPTION meta-information ... OK
* installing the package to build vignettes
* creating vignettes ... ERROR
Quitting from lines 66-74 (use-case.Rmd) 
Error: processing vignette 'use-case.Rmd' failed with diagnostics:
Not Found (HTTP 404).
Execution halted
Installation failed: Command failed (1)

---------------------------------------------------------------------------

Do you have any idea what is going wrong? I've installed devtools already.

**Comment by adamhsparks** [comment]
Hi, sorry about that. It's not R related. Error 404 is that the web URL is not found when building the vignette. NASA moved the POWER to a new API and new URL to retrieve the data. I've not yet completed the updates to the package yet. I've been working on it, but it's not yet complete.

I've merged the `devel` branch with `master` and update the docs to reflect that this repository is still under development now due to these changes.

You can try installing this new version of `nasapower` if you like, but don't expect everything to work properly yet.
