### ISSUE TITLE
CSV File Not Created

### ISSUE THREAD

**Issue by evanmusick** [adamhsparks/nasapower#18]
Repeatedly getting  the following error. Nothing seems to be wrong on https://power.larc.nasa.gov/

Error: 
A CSV file was not created, this is a server error.
The server may not be responding or is currently responding improperly.
Please check <https://power.larc.nasa.gov/> for notifications if
you repeatedly get this error. 

Testing with:
power <- get_power(community = "AG",
                   lonlat = c(-179.5, -89.5),
                   pars = c("RH2M", "T2M"),
                   dates = "1985-01-01",
                    temporal_average = "DAILY")

**Comment by adamhsparks** [comment]
Yes, I'm aware. NASA decided to make an unannounced change to the API that affects how this package ingests the data that is generated. Now instead of generating a clean rectangular CSV file it has additional information in the header.

I am communicating with the POWER team about the changes so I fix this as quickly as I can. It will take me a bit though, sorry. I've some other issues that take priority right now.

**Comment by evanmusick** [comment]
Thanks for the response! I'm a bit new to Github and unfamiliar with Issues etiquette, so I apologize if I sounded a bit rude.

**Comment by adamhsparks** [comment]
@evanmusick, this should be working now.

Can you please test it and report back any issues?

ta!

**Comment by evanmusick** [comment]
Success! Thank you very much!
